version: '3'

services:
  php:
    build: docker/php
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
    working_dir: /var/www/html
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test