version: '3'

services:
  php:
    build: docker/php
    volumes:
      - ./src:/var/www/
    ports:
      - '80:80'
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test