version: '3'

services:
  php:
    image: php:8.0-apache
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db:/var/lib/mysql